//! Request validation and sequence normalization for the token batcher.

#![allow(clippy::derive_partial_eq_without_eq)]

use core::cell::Cell;

use sml::sml;

/// Maximum number of tokens accepted by one batch request.
pub const MAX_TOKENS: usize = 4096;
/// Maximum sequence identifier representable by a sequence mask.
pub const MAX_SEQ: usize = 256;
/// Number of 64-bit words required for [`MAX_SEQ`] sequence bits.
pub const SEQ_WORDS: usize = MAX_SEQ.div_ceil(64);

/// Caller-owned buffers populated by sequence normalization.
pub struct BatchOutputs<'a> {
    /// Normalized primary sequence identifier for each token.
    pub seq_primary_ids: &'a mut [i32],
    /// Normalized sequence mask rows, stored consecutively by token.
    pub seq_masks: &'a mut [u64],
    /// Position output storage reserved for later batcher phases.
    pub positions: &'a mut [i32],
    /// Output-mask storage reserved for later batcher phases.
    pub output_mask: &'a mut [i8],
}

impl core::fmt::Debug for BatchOutputs<'_> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter
            .debug_struct("BatchOutputs")
            .field("seq_primary_ids_len", &self.seq_primary_ids.len())
            .field("seq_masks_len", &self.seq_masks.len())
            .field("positions_len", &self.positions.len())
            .field("output_mask_len", &self.output_mask.len())
            .finish()
    }
}

/// A token-batcher request accepted by the validation entry slice.
pub struct BatchRequest<'a> {
    /// Token identifiers to validate and batch.
    pub token_ids: &'a [i32],
    /// Vocabulary size. Zero disables vocabulary checking, while negative
    /// values are invalid.
    pub vocab_size: i32,
    /// Optional flattened input sequence-mask rows.
    pub seq_masks: Option<&'a [u64]>,
    /// Number of words in each supplied sequence-mask row.
    pub seq_mask_words: usize,
    /// Optional input primary sequence identifiers.
    pub seq_primary_ids: Option<&'a [i32]>,
    /// Optional positions input. Positions are not generated by this slice,
    /// but its shape participates in capacity validation.
    pub positions: Option<&'a [i32]>,
    /// Required caller-owned output buffers.
    pub outputs: BatchOutputs<'a>,
}

impl core::fmt::Debug for BatchRequest<'_> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter
            .debug_struct("BatchRequest")
            .field("token_ids_len", &self.token_ids.len())
            .field("vocab_size", &self.vocab_size)
            .field("seq_masks", &self.seq_masks.map(<[u64]>::len))
            .field("seq_mask_words", &self.seq_mask_words)
            .field("seq_primary_ids", &self.seq_primary_ids.map(<[i32]>::len))
            .field("positions", &self.positions.map(<[i32]>::len))
            .field("outputs", &self.outputs)
            .finish()
    }
}

/// Successful output from the request-validation and normalization slice.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BatchResult {
    /// Number of validated tokens.
    pub token_count: usize,
    /// Number of words in each normalized sequence-mask row.
    pub seq_mask_words: usize,
}

/// Explicit outcomes for this bounded batcher slice.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BatchError {
    /// The request failed a required-output, count, capacity, vocabulary, or
    /// sequence-payload check.
    InvalidRequest,
    /// A state-machine transition or guarded action violated the local
    /// contract.
    Internal,
    /// An event was not expected in the active state.
    UnexpectedEvent,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum DispatchError {
    None,
    InvalidRequest,
    Internal,
}

#[derive(Debug)]
struct DispatchContext {
    error: Cell<DispatchError>,
    normalized_seq_mask_words: Cell<usize>,
}

impl DispatchContext {
    const fn new() -> Self {
        Self {
            error: Cell::new(DispatchError::None),
            normalized_seq_mask_words: Cell::new(1),
        }
    }
}

#[derive(Clone, Copy, Debug)]
struct RequestView<'a> {
    token_ids: &'a [i32],
    vocab_size: i32,
    seq_masks: Option<&'a [u64]>,
    seq_mask_words: usize,
    seq_primary_ids: Option<&'a [i32]>,
    positions: Option<&'a [i32]>,
}

#[derive(Clone, Copy)]
struct OutputCells<'a> {
    seq_primary_ids: &'a [Cell<i32>],
    seq_masks: &'a [Cell<u64>],
    positions: &'a [Cell<i32>],
    output_mask: &'a [Cell<i8>],
}

#[derive(Clone, Copy)]
pub struct BatchRuntime<'a> {
    request: RequestView<'a>,
    outputs: OutputCells<'a>,
    context: &'a DispatchContext,
}

#[derive(Clone, Copy, Debug, Default)]
pub struct Context {
    unexpected: bool,
}

sml! {
    TokenBatcher {
        "request_decision"_s <= *"ready"_s + Batch(&'dispatch BatchRuntime<'dispatch>) / begin_batch,
        "request_validation_probe"_s <= "request_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>),
        "request_outputs_decision"_s <= "request_validation_probe"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>),
        "request_token_counts_decision"_s <= "request_outputs_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_outputs_present],
        "errored"_s <= "request_outputs_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_outputs_missing] / mark_invalid_request,
        "request_capacities_decision"_s <= "request_token_counts_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_token_counts_valid],
        "errored"_s <= "request_token_counts_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_token_counts_invalid] / mark_invalid_request,
        "request_token_ids_decision"_s <= "request_capacities_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_capacities_valid],
        "errored"_s <= "request_capacities_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_capacities_invalid] / mark_invalid_request,
        "request_seq_payload_decision"_s <= "request_token_ids_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_token_ids_in_vocab],
        "errored"_s <= "request_token_ids_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_token_ids_out_of_vocab] / mark_invalid_request,
        "seq_mode_decision"_s <= "request_seq_payload_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_seq_payload_valid],
        "errored"_s <= "request_seq_payload_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [request_seq_payload_invalid] / mark_invalid_request,
        "seq_from_masks"_s <= "seq_mode_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [seq_mode_masks] / normalize_seq_from_masks,
        "seq_from_primary_ids"_s <= "seq_mode_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [seq_mode_primary_ids] / normalize_seq_from_primary_ids,
        "seq_default"_s <= "seq_mode_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) [seq_mode_default] / normalize_seq_default,
        "errored"_s <= "seq_mode_decision"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>) / mark_internal_error,

        // This lane ends after sequence normalization; later batcher phases
        // are intentionally owned by a separate implementation slice.
        "ready"_s <= "seq_from_masks"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>),
        "ready"_s <= "seq_from_primary_ids"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>),
        "ready"_s <= "seq_default"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>),
        "ready"_s <= "errored"_s + completion<Batch>(&'dispatch BatchRuntime<'dispatch>),

        // Exercise the explicit wildcard outcome without exposing generated
        // machine details in the public API.
        "errored"_s <= "errored"_s + UnexpectedProbe,
        "ready"_s <= "ready"_s + unexpected<_> / mark_unexpected,
    }
}

impl TokenBatcherStateMachine<Context> {
    pub(super) fn dispatch(
        &mut self,
        request: BatchRequest<'_>,
    ) -> Result<BatchResult, BatchError> {
        let BatchRequest {
            token_ids,
            vocab_size,
            seq_masks: input_seq_masks,
            seq_mask_words,
            seq_primary_ids: input_seq_primary_ids,
            positions: input_positions,
            outputs,
        } = request;

        let seq_primary_ids_out = Cell::from_mut(outputs.seq_primary_ids).as_slice_of_cells();
        let seq_masks_out = Cell::from_mut(outputs.seq_masks).as_slice_of_cells();
        let positions_out = Cell::from_mut(outputs.positions).as_slice_of_cells();
        let output_mask_out = Cell::from_mut(outputs.output_mask).as_slice_of_cells();
        let context = DispatchContext::new();
        let runtime = BatchRuntime {
            request: RequestView {
                token_ids,
                vocab_size,
                seq_masks: input_seq_masks,
                seq_mask_words,
                seq_primary_ids: input_seq_primary_ids,
                positions: input_positions,
            },
            outputs: OutputCells {
                seq_primary_ids: seq_primary_ids_out,
                seq_masks: seq_masks_out,
                positions: positions_out,
                output_mask: output_mask_out,
            },
            context: &context,
        };

        if self
            .process_event(TokenBatcherEvents::Batch(&runtime))
            .is_err()
        {
            return Err(BatchError::Internal);
        }

        match context.error.get() {
            DispatchError::None => Ok(BatchResult {
                token_count: token_ids.len(),
                seq_mask_words: context.normalized_seq_mask_words.get(),
            }),
            DispatchError::InvalidRequest => Err(BatchError::InvalidRequest),
            DispatchError::Internal => Err(BatchError::Internal),
        }
    }

    pub(super) fn dispatch_unexpected(&mut self) -> Result<(), BatchError> {
        self.context_mut().unexpected = false;
        if self
            .process_event(TokenBatcherEvents::UnexpectedProbe)
            .is_err()
        {
            return Err(BatchError::Internal);
        }
        if self.context().unexpected {
            Err(BatchError::UnexpectedEvent)
        } else {
            Ok(())
        }
    }
}

impl TokenBatcherStateMachineContext for Context {
    fn begin_batch(&mut self, event: &BatchRuntime<'_>) -> Result<(), ()> {
        self.unexpected = false;
        event.context.error.set(DispatchError::None);
        event.context.normalized_seq_mask_words.set(1);
        Ok(())
    }

    fn mark_invalid_request(&mut self, event: &BatchRuntime<'_>) -> Result<(), ()> {
        event.context.error.set(DispatchError::InvalidRequest);
        Ok(())
    }

    fn mark_internal_error(&mut self, event: &BatchRuntime<'_>) -> Result<(), ()> {
        event.context.error.set(DispatchError::Internal);
        Ok(())
    }

    fn mark_unexpected(&mut self) -> Result<(), ()> {
        self.unexpected = true;
        Ok(())
    }

    fn normalize_seq_from_masks(&mut self, event: &BatchRuntime<'_>) -> Result<(), ()> {
        let Some(input_masks) = event.request.seq_masks.filter(|masks| {
            masks.len() >= event.request.token_ids.len() * event.request.seq_mask_words
        }) else {
            return Err(());
        };
        let words = event.request.seq_mask_words;
        event.context.normalized_seq_mask_words.set(words);
        for token_index in 0..event.request.token_ids.len() {
            let start = token_index * words;
            let input_row = &input_masks[start..start + words];
            let output_row = &event.outputs.seq_masks[start..start + words];
            for (output_word, input_word) in output_row.iter().zip(input_row) {
                output_word.set(*input_word);
            }
            let mut primary = 0usize;
            for (word_index, input_word) in input_row.iter().enumerate() {
                if *input_word != 0 {
                    primary = word_index * 64 + input_word.trailing_zeros() as usize;
                    break;
                }
            }
            let primary = i32::try_from(primary).map_err(|_| ())?;
            event.outputs.seq_primary_ids[token_index].set(primary);
        }
        Ok(())
    }

    fn normalize_seq_from_primary_ids(&mut self, event: &BatchRuntime<'_>) -> Result<(), ()> {
        let Some(input_ids) = event
            .request
            .seq_primary_ids
            .filter(|ids| ids.len() >= event.request.token_ids.len())
        else {
            return Err(());
        };
        event.context.normalized_seq_mask_words.set(1);
        for (token_index, input_id) in input_ids
            .iter()
            .copied()
            .take(event.request.token_ids.len())
            .enumerate()
        {
            event.outputs.seq_primary_ids[token_index].set(input_id);
            let bit = u32::try_from(input_id).map_err(|_| ())?;
            event.outputs.seq_masks[token_index].set(1u64 << bit);
        }
        Ok(())
    }

    fn normalize_seq_default(&mut self, event: &BatchRuntime<'_>) -> Result<(), ()> {
        event.context.normalized_seq_mask_words.set(1);
        for token_index in 0..event.request.token_ids.len() {
            event.outputs.seq_primary_ids[token_index].set(0);
            event.outputs.seq_masks[token_index].set(1);
        }
        Ok(())
    }

    fn request_outputs_present(&self, _event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(true)
    }

    fn request_outputs_missing(&self, _event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(false)
    }

    fn request_token_counts_valid(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        let count = event.request.token_ids.len();
        Ok(count > 0 && count <= MAX_TOKENS)
    }

    fn request_token_counts_invalid(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(!self.request_token_counts_valid(event)?)
    }

    fn request_capacities_valid(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        let count = event.request.token_ids.len();
        let mask_words = effective_mask_words(&event.request);
        let Some(mask_capacity) = count.checked_mul(mask_words) else {
            return Ok(false);
        };
        let Some(positions_count) = normalized_positions_count(&event.request) else {
            return Ok(false);
        };
        Ok(event.outputs.seq_primary_ids.len() >= count
            && event.outputs.seq_masks.len() >= mask_capacity
            && event.outputs.positions.len() >= positions_count
            && event.outputs.output_mask.len() >= count)
    }

    fn request_capacities_invalid(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(!self.request_capacities_valid(event)?)
    }

    fn request_token_ids_in_vocab(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        let vocab_size = event.request.vocab_size;
        if vocab_size < 0 {
            return Ok(false);
        }
        if vocab_size == 0 {
            return Ok(true);
        }
        Ok(event
            .request
            .token_ids
            .iter()
            .all(|token_id| *token_id >= 0 && *token_id < vocab_size))
    }

    fn request_token_ids_out_of_vocab(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(!self.request_token_ids_in_vocab(event)?)
    }

    fn request_seq_payload_valid(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(seq_payload_valid(&event.request))
    }

    fn request_seq_payload_invalid(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(!self.request_seq_payload_valid(event)?)
    }

    fn seq_mode_masks(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(has_seq_masks_input(&event.request))
    }

    fn seq_mode_primary_ids(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(!has_seq_masks_input(&event.request) && has_seq_primary_input(&event.request))
    }

    fn seq_mode_default(&self, event: &BatchRuntime<'_>) -> Result<bool, ()> {
        Ok(!has_seq_masks_input(&event.request) && !has_seq_primary_input(&event.request))
    }
}

fn has_seq_masks_input(request: &RequestView<'_>) -> bool {
    request
        .seq_masks
        .is_some_and(|masks| masks.len() >= request.token_ids.len())
}

fn has_seq_primary_input(request: &RequestView<'_>) -> bool {
    request
        .seq_primary_ids
        .is_some_and(|ids| ids.len() >= request.token_ids.len())
}

fn effective_mask_words(request: &RequestView<'_>) -> usize {
    if has_seq_masks_input(request) {
        request.seq_mask_words
    } else {
        1
    }
}

fn positions_stride(request: &RequestView<'_>) -> i32 {
    let Some(positions) = request.positions else {
        return 0;
    };
    let count = request.token_ids.len();
    if count
        .checked_mul(3)
        .is_some_and(|required| positions.len() >= required)
    {
        3
    } else if positions.len() >= count {
        1
    } else {
        -1
    }
}

fn normalized_positions_count(request: &RequestView<'_>) -> Option<usize> {
    match positions_stride(request) {
        -1 => None,
        3 => request.token_ids.len().checked_mul(3),
        0 | 1 => Some(request.token_ids.len()),
        _ => None,
    }
}

fn seq_payload_valid(request: &RequestView<'_>) -> bool {
    let count = request.token_ids.len();
    let has_masks = has_seq_masks_input(request);
    let has_primary = has_seq_primary_input(request);
    let mask_words_valid = request.seq_mask_words > 0 && request.seq_mask_words <= SEQ_WORDS;

    let masks_non_empty = if has_masks {
        if request.seq_mask_words == 0 {
            false
        } else if let Some(input_masks) = request.seq_masks {
            let Some(required) = count.checked_mul(request.seq_mask_words) else {
                return false;
            };
            input_masks.len() >= required
                && input_masks
                    .chunks_exact(request.seq_mask_words)
                    .take(count)
                    .all(|row| row.iter().any(|word| *word != 0))
        } else {
            false
        }
    } else {
        true
    };
    let masks_ok = !has_masks || (mask_words_valid && masks_non_empty);

    let mask_limit = effective_mask_words(request).saturating_mul(64);
    let primary_range_ok = !has_primary
        || request.seq_primary_ids.is_some_and(|ids| {
            ids.iter().take(count).all(|id| {
                *id >= 0 && usize::try_from(*id).is_ok_and(|sequence_id| sequence_id < mask_limit)
            })
        });
    let primary_in_mask_ok = if has_masks && has_primary {
        if request.seq_mask_words == 0 {
            false
        } else {
            let Some(input_masks) = request.seq_masks else {
                return false;
            };
            let Some(input_ids) = request.seq_primary_ids else {
                return false;
            };
            input_masks
                .chunks_exact(request.seq_mask_words)
                .zip(input_ids.iter().copied())
                .take(count)
                .all(|(row, id)| mask_has_bit(row, id))
        }
    } else {
        true
    };

    masks_ok && primary_range_ok && primary_in_mask_ok
}

const fn mask_has_bit(mask: &[u64], sequence_id: i32) -> bool {
    if sequence_id < 0 {
        return false;
    }
    let sequence_id = sequence_id.unsigned_abs();
    let word = (sequence_id / 64) as usize;
    word < mask.len() && (mask[word] & (1u64 << (sequence_id % 64))) != 0
}
