[package]
name = "emel-gguf"
description = "GGUF container support for emel."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sml = { workspace = true }

[dev-dependencies]
allocation-counter = "=0.8.1"
