//! Generic kernel actors and data-plane operations.

pub mod activation;
mod actor;
pub mod backward;
pub mod binary;
pub mod broadcast;
pub mod conv;
pub mod conv_transpose_1d;
pub mod count_equal;
pub mod custom;
pub mod diag;
pub mod elementwise;
pub mod event;
pub mod f16_matmul;
pub mod fill_arange;
pub mod flash_attn;
pub mod generic;
pub mod get_rows;
pub mod gla;
pub mod glu;
pub mod group_norm;
pub mod im2col;
pub mod indexed;
pub mod linalg;
pub mod matmul;
pub mod normalization;
pub mod pad;
pub mod pool;
pub mod positional;
pub mod power;
pub mod quant;
pub mod quant_more;
pub mod reductions;
pub mod rel;
pub mod reorder;
pub mod rope;
pub mod rwkv;
pub mod sequence;
pub mod shape;
pub mod sm;
pub mod sortformer;
pub mod ssm;
pub mod tensor_view;
pub mod train;
pub mod unary;
pub mod window;

pub use actor::{Error, Kernel};
