//! Canonical Sortformer execution-contract transition table.

#![allow(clippy::derive_partial_eq_without_eq)]

use super::actor::{
    BeginRuntime, FinishRuntime, ObserveRuntime, ReleaseRuntime, ResetRuntime, UnexpectedRuntime,
    VisitRuntime,
};
use super::hparams::HparamLoadRuntime;
use super::query::{NameOperation, NameRequest};
use sml::sml;

sml! {
    SortformerMachine<'dispatch> {
        "state_scanning"_s <= *"state_empty"_s + Begin(BeginRuntime<'dispatch>) [guard_begin_valid] / effect_begin,
        "state_rejected"_s <= "state_empty"_s + Begin(BeginRuntime<'dispatch>) [guard_begin_invalid] / effect_model_invalid,
        "state_rejected"_s <= "state_empty"_s + Begin(BeginRuntime<'dispatch>) [guard_begin_storage_unavailable] / effect_storage_unavailable_begin,
        "state_scanning"_s <= "state_scanning"_s + Begin(BeginRuntime<'dispatch>) / effect_busy_begin,
        "state_ready"_s <= "state_ready"_s + Begin(BeginRuntime<'dispatch>) / effect_busy_begin,

        "state_scan_error"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_observation_index_invalid] / effect_invalid_request,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_feature_first_fits] / effect_feature_first,
        "state_scan_error"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_feature_first_capacity] / effect_capacity,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_feature_additional] / effect_feature_additional,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_encoder_first_fits] / effect_encoder_first,
        "state_scan_error"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_encoder_first_capacity] / effect_capacity,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_encoder_additional] / effect_encoder_additional,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_modules_first_fits] / effect_modules_first,
        "state_scan_error"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_modules_first_capacity] / effect_capacity,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_modules_additional] / effect_modules_additional,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_transformer_first_fits] / effect_transformer_first,
        "state_scan_error"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_transformer_first_capacity] / effect_capacity,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_transformer_additional] / effect_transformer_additional,
        "state_scanning"_s <= "state_scanning"_s + Observe(ObserveRuntime<'dispatch>) [guard_observation_ignored] / effect_observation_ignored,
        "state_rejected"_s <= "state_rejected"_s + Observe(ObserveRuntime<'dispatch>) / effect_preserve_observe,
        "state_scan_error"_s <= "state_scan_error"_s + Observe(ObserveRuntime<'dispatch>) / effect_preserve_observe,
        "state_empty"_s <= "state_empty"_s + Observe(ObserveRuntime<'dispatch>) [guard_storage_available_observe] / effect_invalid_request,
        "state_empty"_s <= "state_empty"_s + Observe(ObserveRuntime<'dispatch>) [guard_storage_unavailable_observe] / effect_storage_unavailable_observe,
        "state_ready"_s <= "state_ready"_s + Observe(ObserveRuntime<'dispatch>) / effect_busy_observe,

        "state_ready"_s <= "state_scanning"_s + Finish(FinishRuntime<'dispatch>) [guard_families_complete] / effect_finish,
        "state_empty"_s <= "state_scanning"_s + Finish(FinishRuntime<'dispatch>) [guard_families_incomplete] / effect_model_invalid_finish,
        "state_empty"_s <= "state_rejected"_s + Finish(FinishRuntime<'dispatch>) / effect_preserve_finish,
        "state_empty"_s <= "state_scan_error"_s + Finish(FinishRuntime<'dispatch>) / effect_preserve_finish,
        "state_empty"_s <= "state_empty"_s + Finish(FinishRuntime<'dispatch>) [guard_storage_available_finish] / effect_invalid_finish,
        "state_empty"_s <= "state_empty"_s + Finish(FinishRuntime<'dispatch>) [guard_storage_unavailable_finish] / effect_storage_unavailable_finish,
        "state_ready"_s <= "state_ready"_s + Finish(FinishRuntime<'dispatch>) / effect_busy_finish,

        "state_ready"_s <= "state_ready"_s + Visit(VisitRuntime<'dispatch>) / effect_visit,
        "state_empty"_s <= "state_empty"_s + Visit(VisitRuntime<'dispatch>) [guard_storage_available_visit] / effect_invalid_visit,
        "state_empty"_s <= "state_empty"_s + Visit(VisitRuntime<'dispatch>) [guard_storage_unavailable_visit] / effect_storage_unavailable,
        "state_scanning"_s <= "state_scanning"_s + Visit(VisitRuntime<'dispatch>) / effect_busy_visit,

        "state_empty"_s <= "state_scanning"_s + Reset(ResetRuntime<'dispatch>) / effect_reset_storage,
        "state_empty"_s <= "state_ready"_s + Reset(ResetRuntime<'dispatch>) / effect_reset_storage,
        "state_empty"_s <= "state_rejected"_s + Reset(ResetRuntime<'dispatch>) / effect_reset_storage,
        "state_empty"_s <= "state_scan_error"_s + Reset(ResetRuntime<'dispatch>) / effect_reset_storage,
        "state_empty"_s <= "state_empty"_s + Reset(ResetRuntime<'dispatch>) [guard_storage_available_reset] / effect_reset_storage,
        "state_empty"_s <= "state_empty"_s + Reset(ResetRuntime<'dispatch>) [guard_storage_unavailable_reset] / effect_reset_without_storage,

        "state_empty"_s <= "state_empty"_s + Release(ReleaseRuntime<'dispatch>) [guard_storage_available_release] / effect_release_storage,
        "state_empty"_s <= "state_empty"_s + Release(ReleaseRuntime<'dispatch>) [guard_storage_unavailable_release] / effect_storage_unavailable_release,
        "state_scanning"_s <= "state_scanning"_s + Release(ReleaseRuntime<'dispatch>) / effect_busy_release,
        "state_ready"_s <= "state_ready"_s + Release(ReleaseRuntime<'dispatch>) / effect_busy_release,
        "state_rejected"_s <= "state_rejected"_s + Release(ReleaseRuntime<'dispatch>) / effect_busy_release,
        "state_scan_error"_s <= "state_scan_error"_s + Release(ReleaseRuntime<'dispatch>) / effect_busy_release,

        "other"_s <= "other"_s + event<UnexpectedRuntime> [guard_never],
        "state_empty"_s <= "state_empty"_s + unexpected_event<_> / effect_unexpected,
        "state_scanning"_s <= "state_scanning"_s + unexpected_event<_> / effect_unexpected,
        "state_ready"_s <= "state_ready"_s + unexpected_event<_> / effect_unexpected,
        "state_rejected"_s <= "state_rejected"_s + unexpected_event<_> / effect_unexpected,
        "state_scan_error"_s <= "state_scan_error"_s + unexpected_event<_> / effect_unexpected,
    }
}

sml! {
    SortformerHparams<'dispatch> {
        "state_architecture_decision"_s <= *"state_idle"_s + Load(HparamLoadRuntime<'dispatch>) / effect_query_architecture,
        "state_source_decision"_s <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_architecture_valid] / effect_query_source,
        X <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_architecture_invalid] / effect_contract,
        X <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_architecture_missing] / effect_missing,
        X <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range] / effect_range,
        X <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_architecture_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_scheme_decision"_s <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_present] / effect_query_scheme,
        X <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_contract] / effect_contract,
        X <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_missing] / effect_missing,
        X <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range] / effect_range,
        X <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_source_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_outtype_decision"_s <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_present] / effect_query_outtype,
        X <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_contract] / effect_contract,
        X <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_missing] / effect_missing,
        X <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range] / effect_range,
        X <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_scheme_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_original_decision"_s <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_present] / effect_query_original,
        X <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_contract] / effect_contract,
        X <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_string_missing] / effect_missing,
        X <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range] / effect_range,
        X <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_outtype_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_tensor_decision"_s <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_positive] / effect_assign_original_query_tensor,
        X <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_nonpositive] / effect_range,
        X <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_missing,
        X <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_original_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_skipped_decision"_s <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_positive] / effect_assign_tensor_query_skipped,
        X <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_nonpositive] / effect_range,
        X <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_missing,
        X <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_tensor_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_sample_primary_decision"_s <= "state_skipped_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_skipped_query_sample_primary,
        "state_sample_primary_decision"_s <= "state_skipped_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_default_skipped_query_sample_primary,
        X <= "state_skipped_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_skipped_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_skipped_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_skipped_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_speaker_primary_decision"_s <= "state_sample_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_sample_query_speaker_primary,
        "state_sample_fallback_decision"_s <= "state_sample_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_sample_fallback,
        X <= "state_sample_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_sample_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_sample_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_sample_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_speaker_primary_decision"_s <= "state_sample_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_sample_query_speaker_primary,
        "state_speaker_primary_decision"_s <= "state_sample_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_speaker_primary,
        X <= "state_sample_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_sample_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_sample_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_sample_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_chunk_decision"_s <= "state_speaker_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_speaker_query_chunk,
        "state_speaker_secondary_decision"_s <= "state_speaker_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_speaker_secondary,
        X <= "state_speaker_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_speaker_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_speaker_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_speaker_primary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_chunk_decision"_s <= "state_speaker_secondary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_speaker_query_chunk,
        "state_speaker_fallback_decision"_s <= "state_speaker_secondary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_speaker_fallback,
        X <= "state_speaker_secondary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_speaker_secondary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_speaker_secondary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_speaker_secondary_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_chunk_decision"_s <= "state_speaker_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_speaker_query_chunk,
        "state_chunk_decision"_s <= "state_speaker_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_chunk,
        X <= "state_speaker_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_speaker_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_speaker_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_speaker_fallback_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_right_decision"_s <= "state_chunk_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_chunk_query_right,
        "state_right_decision"_s <= "state_chunk_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_right,
        X <= "state_chunk_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_chunk_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_chunk_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_chunk_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_fifo_decision"_s <= "state_right_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_right_query_fifo,
        "state_fifo_decision"_s <= "state_right_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_fifo,
        X <= "state_right_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_right_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_right_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_right_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_update_decision"_s <= "state_fifo_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_fifo_query_update,
        "state_update_decision"_s <= "state_fifo_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_update,
        X <= "state_fifo_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_fifo_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_fifo_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_fifo_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_len_decision"_s <= "state_update_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_update_query_len,
        "state_len_decision"_s <= "state_update_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_query_len,
        X <= "state_update_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_update_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_update_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_update_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_validate_sample"_s <= "state_len_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_i32] / effect_assign_len_validate_sample,
        "state_validate_sample"_s <= "state_len_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_unsigned_missing] / effect_validate_sample,
        X <= "state_len_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_wrong_kind] / effect_wrong_kind,
        X <= "state_len_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_range_or_value_range] / effect_range,
        X <= "state_len_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_internal] / effect_internal,
        X <= "state_len_decision"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_query_other] / effect_query,

        "state_validate_speaker"_s <= "state_validate_sample"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_sample_valid] / effect_validate_speaker,
        X <= "state_validate_sample"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_sample_invalid] / effect_contract,
        "state_validate_chunk"_s <= "state_validate_speaker"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_speaker_valid] / effect_validate_chunk,
        X <= "state_validate_speaker"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_speaker_invalid] / effect_contract,
        "state_validate_right"_s <= "state_validate_chunk"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_chunk_valid] / effect_validate_right,
        X <= "state_validate_chunk"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_chunk_invalid] / effect_contract,
        "state_validate_fifo"_s <= "state_validate_right"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_right_valid] / effect_validate_fifo,
        X <= "state_validate_right"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_right_invalid] / effect_contract,
        "state_validate_update"_s <= "state_validate_fifo"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_fifo_valid] / effect_validate_update,
        X <= "state_validate_fifo"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_fifo_invalid] / effect_contract,
        "state_validate_len"_s <= "state_validate_update"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_update_valid] / effect_validate_len,
        X <= "state_validate_update"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_update_invalid] / effect_contract,
        X <= "state_validate_len"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_len_valid] / effect_success,
        X <= "state_validate_len"_s + completion<Load>(HparamLoadRuntime<'dispatch>) [guard_len_invalid] / effect_contract,

        "other"_s <= "other"_s + event<UnexpectedRuntime> [guard_never],
        X <= "state_idle"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_architecture_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_source_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_scheme_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_outtype_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_original_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_tensor_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_skipped_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_sample_primary_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_sample_fallback_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_speaker_primary_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_speaker_secondary_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_speaker_fallback_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_chunk_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_right_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_fifo_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_update_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_len_decision"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_sample"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_speaker"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_chunk"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_right"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_fifo"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_update"_s + unexpected_event<_> / effect_unexpected,
        X <= "state_validate_len"_s + unexpected_event<_> / effect_unexpected,
    }
}

sml! {
    SortformerNameQuery<'query, 'data, O>
    where
        'data: 'query,
        O: NameOperation + 'data,
    {
        X <= *"state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_storage_unavailable] / effect_storage_unavailable,
        X <= "state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_invalid] / effect_invalid,
        X <= "state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_busy] / effect_busy,
        X <= "state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_feature] / effect_apply_feature,
        X <= "state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_encoder] / effect_apply_encoder,
        X <= "state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_modules] / effect_apply_modules,
        X <= "state_ready"_s + event<&'query mut NameRequest<'data, O>> [guard_transformer] / effect_apply_transformer,
        X <= "state_ready"_s + unexpected_event<_> / effect_unexpected,
    }
}
